version: 2
updates:
  - directory: /
    schedule:
      interval: weekly
    package-ecosystem: github-actions
    commit-message:
      prefix: "chore(github-actions)"
  - directory: /
    schedule:
      interval: weekly
    package-ecosystem: cargo
    commit-message:
      prefix: "chore(cargo)"
