[alias]
# Do not append `--` or it will break IDEs
ck = "check --workspace --all-targets --all-features --locked"
lint = "clippy --workspace --all-targets --all-features"
codecov = "llvm-cov nextest --workspace --ignore-filename-regex tasks"
rule = "run -p rulegen"

[build]
rustflags = ["-C", "target-cpu=native"]
